"""Syft SBOM generation rules and aspect."""

SUPPORTED_FORMATS = [
    "spdx-json",
    "spdx-tag-value",
    "cyclonedx-json",
    "cyclonedx-xml",
    "syft-json",
    "github-json",
]

# File extensions for each format
_FORMAT_EXTENSIONS = {
    "spdx-json": "spdx.json",
    "spdx-tag-value": "spdx",
    "cyclonedx-json": "cdx.json",
    "cyclonedx-xml": "cdx.xml",
    "syft-json": "syft.json",
    "github-json": "github.json",
}

SyftSBOMInfo = provider(
    doc = "SBOM generated by Syft, propagated by syft_sbom_aspect.",
    fields = {
        "sbom": "File containing the SBOM in spdx-json format",
    },
)

def _run_syft(actions, syft, tarball, output, format, label):
    """Shared helper to run syft and produce an SBOM."""
    actions.run_shell(
        inputs = [tarball],
        outputs = [output],
        tools = [syft],
        command = """
export SYFT_CHECK_FOR_APP_UPDATE=false
export SYFT_CACHE_DIR=$(mktemp -d)
{syft} "$PWD/{tarball}" -o {format}={output}
""".format(
            tarball = tarball.path,
            output = output.path,
            syft = syft.path,
            format = format,
        ),
        mnemonic = "SyftSBOM",
        progress_message = "Generating SBOM (%s) for %s" % (format, label),
    )

def _get_tarball(target):
    """Extract OCI tarball from a target, or return None."""
    if OutputGroupInfo not in target:
        return None
    output_group_info = target[OutputGroupInfo]
    if hasattr(output_group_info, "oci_tarball"):
        return output_group_info.oci_tarball.to_list()[0]
    elif hasattr(output_group_info, "tarball"):
        return output_group_info.tarball.to_list()[0]
    return None

def _get_syft_binary(ctx):
    """Get syft binary from explicit attr or toolchain."""
    if hasattr(ctx.attr, "syft") and ctx.attr.syft:
        return ctx.executable.syft
    toolchain_info = ctx.toolchains["@syft.bzl//syft:toolchain"]
    if not toolchain_info:
        return None
    return toolchain_info.syft_info.syft_binary

# ---------- Rule ----------

def _syft_sbom_impl(ctx):
    """Generate SBOM from OCI image using syft."""
    tarball = _get_tarball(ctx.attr.image)
    if tarball == None:
        fail("image must be a target with an 'oci_tarball' (rules_img) or 'tarball' (rules_oci) output group")
    output = ctx.outputs.sbom

    syft = _get_syft_binary(ctx)
    if syft == None:
        fail("No syft toolchain found. Either set the 'syft' attribute or register the syft toolchain.")

    _run_syft(ctx.actions, syft, tarball, output, ctx.attr.format, ctx.label)

    return [DefaultInfo(files = depset([output]))]

def _sbom_output(name, format):
    """Generate output filename based on format."""
    ext = _FORMAT_EXTENSIONS.get(format, "json")
    return {
        "sbom": "%s.%s" % (name, ext),
    }

syft_sbom = rule(
    implementation = _syft_sbom_impl,
    attrs = {
        "image": attr.label(
            mandatory = True,
            doc = "OCI image target with an 'oci_tarball' (rules_img) or 'tarball' (rules_oci) output group",
        ),
        "format": attr.string(
            default = "spdx-json",
            values = SUPPORTED_FORMATS,
            doc = "Output format for the SBOM. One of: " + ", ".join(SUPPORTED_FORMATS),
        ),
        "syft": attr.label(
            executable = True,
            cfg = "exec",
            doc = "Optional: custom syft binary. If not set, uses toolchain.",
        ),
    },
    outputs = _sbom_output,
    toolchains = [
        config_common.toolchain_type("@syft.bzl//syft:toolchain", mandatory = False),
    ],
    doc = """Generate SBOM from OCI image using Syft.

This rule generates a Software Bill of Materials (SBOM) from an OCI container image
using [Syft](https://github.com/anchore/syft).

Example:
    ```starlark
    load("@syft.bzl", "syft_sbom")

    syft_sbom(
        name = "my_sbom",
        image = ":my_oci_image",
        format = "spdx-json",
    )
    ```
""",
)

# ---------- Aspect ----------

def _syft_sbom_aspect_impl(target, ctx):
    """Aspect that generates SBOM for OCI image targets."""
    tarball = _get_tarball(target)
    if tarball == None:
        return []

    toolchain_info = ctx.toolchains["@syft.bzl//syft:toolchain"]
    if not toolchain_info:
        return []
    syft = toolchain_info.syft_info.syft_binary

    output = ctx.actions.declare_file("{}.spdx.json".format(target.label.name))
    _run_syft(ctx.actions, syft, tarball, output, "spdx-json", target.label)

    return [
        SyftSBOMInfo(sbom = output),
        OutputGroupInfo(sbom = depset([output])),
    ]

syft_sbom_aspect = aspect(
    implementation = _syft_sbom_aspect_impl,
    toolchains = [
        config_common.toolchain_type("@syft.bzl//syft:toolchain", mandatory = False),
    ],
    doc = """Aspect that auto-generates SBOM for OCI image targets.

Attaches to targets with an 'oci_tarball' or 'tarball' output group.
No-ops on all other targets.

Provides:
    - SyftSBOMInfo: with the generated SBOM file
    - OutputGroupInfo: with 'sbom' output group
""",
)
